/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expo;

import java.awt.*;
import java.text.DecimalFormat;
import javax.swing.*;

/**
 *
 * @author MINEDUCYT
 */
public class Prueba extends javax.swing.JFrame {

    private javax.swing.JPanel carritoPanel;
    private java.util.HashMap<String, JSpinner> productosEnCarrito;
    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        
        carritoPanel = new javax.swing.JPanel();
        carritoPanel.setLayout(new javax.swing.BoxLayout(carritoPanel, javax.swing.BoxLayout.Y_AXIS)); // Para alinear los productos hacia abajo
        jScrollPane1.setViewportView(carritoPanel); // Asignar el carritoPanel al JScrollPane

        // Configurar el JScrollPane para que solo tenga scroll vertical y se muestre solo cuando sea necesario
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        productosEnCarrito = new java.util.HashMap<>(); // Inicializar el HashMap
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelFondoProductos = new javax.swing.JPanel();
        panelProducto1 = new expo.PanelRound();
        imagen1 = new javax.swing.JButton();
        nombrePro1 = new javax.swing.JLabel();
        precioPro1 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        panelProducto2 = new expo.PanelRound();
        imagen2 = new javax.swing.JButton();
        nombrePro2 = new javax.swing.JLabel();
        precioPro2 = new javax.swing.JLabel();
        btnAgregar2 = new javax.swing.JButton();
        panelProducto3 = new expo.PanelRound();
        imagen3 = new javax.swing.JButton();
        nombrePro3 = new javax.swing.JLabel();
        precioPro3 = new javax.swing.JLabel();
        btnAgregar3 = new javax.swing.JButton();
        panelProducto4 = new expo.PanelRound();
        imagen4 = new javax.swing.JButton();
        nombrePro4 = new javax.swing.JLabel();
        precioPro4 = new javax.swing.JLabel();
        btnAgregar4 = new javax.swing.JButton();
        panelProducto5 = new expo.PanelRound();
        imagen5 = new javax.swing.JButton();
        nombrePro5 = new javax.swing.JLabel();
        precioPro5 = new javax.swing.JLabel();
        btnAgregar5 = new javax.swing.JButton();
        panelProducto6 = new expo.PanelRound();
        imagen6 = new javax.swing.JButton();
        nombrePro6 = new javax.swing.JLabel();
        precioPro6 = new javax.swing.JLabel();
        btnAgregar6 = new javax.swing.JButton();
        panelProducto7 = new expo.PanelRound();
        imagen7 = new javax.swing.JButton();
        nombrePro7 = new javax.swing.JLabel();
        precioPro7 = new javax.swing.JLabel();
        btnAgregar7 = new javax.swing.JButton();
        panelProducto8 = new expo.PanelRound();
        imagen8 = new javax.swing.JButton();
        nombrePro8 = new javax.swing.JLabel();
        precioPro8 = new javax.swing.JLabel();
        btnAgregar8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelFondoProductos.setBackground(new java.awt.Color(204, 204, 204));

        panelProducto1.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto1.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto1.setRoundBottomLeft(10);
        panelProducto1.setRoundBottomRight(10);
        panelProducto1.setRoundTopLeft(10);
        panelProducto1.setRoundTopRight(10);

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen1.setBorder(null);
        imagen1.setBorderPainted(false);
        imagen1.setContentAreaFilled(false);
        imagen1.setFocusable(false);

        nombrePro1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro1.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro1.setText("<html>Nombre de producto largo1<html>");

        precioPro1.setBackground(new java.awt.Color(255, 255, 255));
        precioPro1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro1.setForeground(new java.awt.Color(0, 0, 0));
        precioPro1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro1.setText("$0.20");

        btnAgregar1.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar1.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar1.setText("+");
        btnAgregar1.setBorder(null);
        btnAgregar1.setBorderPainted(false);
        btnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar1.setFocusable(false);
        btnAgregar1.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto1Layout = new javax.swing.GroupLayout(panelProducto1);
        panelProducto1.setLayout(panelProducto1Layout);
        panelProducto1Layout.setHorizontalGroup(
            panelProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelProducto1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProducto1Layout.createSequentialGroup()
                        .addComponent(precioPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombrePro1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelProducto1Layout.setVerticalGroup(
            panelProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro1)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelProducto2.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto2.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto2.setRoundBottomLeft(10);
        panelProducto2.setRoundBottomRight(10);
        panelProducto2.setRoundTopLeft(10);
        panelProducto2.setRoundTopRight(10);

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen2.setBorder(null);
        imagen2.setBorderPainted(false);
        imagen2.setContentAreaFilled(false);
        imagen2.setFocusable(false);

        nombrePro2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro2.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro2.setText("<html>Nombre de producto largo2<html>");

        precioPro2.setBackground(new java.awt.Color(255, 255, 255));
        precioPro2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro2.setForeground(new java.awt.Color(0, 0, 0));
        precioPro2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro2.setText("$0.40");

        btnAgregar2.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar2.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar2.setText("+");
        btnAgregar2.setBorder(null);
        btnAgregar2.setBorderPainted(false);
        btnAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar2.setFocusable(false);
        btnAgregar2.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto2Layout = new javax.swing.GroupLayout(panelProducto2);
        panelProducto2.setLayout(panelProducto2Layout);
        panelProducto2Layout.setHorizontalGroup(
            panelProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProducto2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto2Layout.createSequentialGroup()
                        .addComponent(precioPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelProducto2Layout.setVerticalGroup(
            panelProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro2)
                    .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelProducto3.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto3.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto3.setRoundBottomLeft(10);
        panelProducto3.setRoundBottomRight(10);
        panelProducto3.setRoundTopLeft(10);
        panelProducto3.setRoundTopRight(10);

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen3.setBorder(null);
        imagen3.setBorderPainted(false);
        imagen3.setContentAreaFilled(false);
        imagen3.setFocusable(false);

        nombrePro3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro3.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro3.setText("<html>Nombre de producto largo3<html>");

        precioPro3.setBackground(new java.awt.Color(255, 255, 255));
        precioPro3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro3.setForeground(new java.awt.Color(0, 0, 0));
        precioPro3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro3.setText("$1.20");

        btnAgregar3.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar3.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar3.setText("+");
        btnAgregar3.setBorder(null);
        btnAgregar3.setBorderPainted(false);
        btnAgregar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar3.setFocusable(false);
        btnAgregar3.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto3Layout = new javax.swing.GroupLayout(panelProducto3);
        panelProducto3.setLayout(panelProducto3Layout);
        panelProducto3Layout.setHorizontalGroup(
            panelProducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelProducto3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto3Layout.createSequentialGroup()
                        .addComponent(precioPro3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelProducto3Layout.setVerticalGroup(
            panelProducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro3)
                    .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelProducto4.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto4.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto4.setRoundBottomLeft(10);
        panelProducto4.setRoundBottomRight(10);
        panelProducto4.setRoundTopLeft(10);
        panelProducto4.setRoundTopRight(10);

        imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen4.setBorder(null);
        imagen4.setBorderPainted(false);
        imagen4.setContentAreaFilled(false);
        imagen4.setFocusable(false);

        nombrePro4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro4.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro4.setText("<html>Nombre de producto largo4<html>");

        precioPro4.setBackground(new java.awt.Color(255, 255, 255));
        precioPro4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro4.setForeground(new java.awt.Color(0, 0, 0));
        precioPro4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro4.setText("$1.00");

        btnAgregar4.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar4.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar4.setText("+");
        btnAgregar4.setBorder(null);
        btnAgregar4.setBorderPainted(false);
        btnAgregar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar4.setFocusable(false);
        btnAgregar4.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto4Layout = new javax.swing.GroupLayout(panelProducto4);
        panelProducto4.setLayout(panelProducto4Layout);
        panelProducto4Layout.setHorizontalGroup(
            panelProducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProducto4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelProducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto4Layout.createSequentialGroup()
                        .addComponent(precioPro4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelProducto4Layout.setVerticalGroup(
            panelProducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro4)
                    .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelProducto5.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto5.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto5.setRoundBottomLeft(10);
        panelProducto5.setRoundBottomRight(10);
        panelProducto5.setRoundTopLeft(10);
        panelProducto5.setRoundTopRight(10);

        imagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen5.setBorder(null);
        imagen5.setBorderPainted(false);
        imagen5.setContentAreaFilled(false);
        imagen5.setFocusable(false);

        nombrePro5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro5.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro5.setText("<html>Nombre de producto largo5<html>");

        precioPro5.setBackground(new java.awt.Color(255, 255, 255));
        precioPro5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro5.setForeground(new java.awt.Color(0, 0, 0));
        precioPro5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro5.setText("$0.00");

        btnAgregar5.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar5.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar5.setText("+");
        btnAgregar5.setBorder(null);
        btnAgregar5.setBorderPainted(false);
        btnAgregar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar5.setFocusable(false);
        btnAgregar5.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto5Layout = new javax.swing.GroupLayout(panelProducto5);
        panelProducto5.setLayout(panelProducto5Layout);
        panelProducto5Layout.setHorizontalGroup(
            panelProducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProducto5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelProducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto5Layout.createSequentialGroup()
                        .addComponent(precioPro5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelProducto5Layout.setVerticalGroup(
            panelProducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro5)
                    .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelProducto6.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto6.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto6.setRoundBottomLeft(10);
        panelProducto6.setRoundBottomRight(10);
        panelProducto6.setRoundTopLeft(10);
        panelProducto6.setRoundTopRight(10);

        imagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen6.setBorder(null);
        imagen6.setBorderPainted(false);
        imagen6.setContentAreaFilled(false);
        imagen6.setFocusable(false);

        nombrePro6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro6.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro6.setText("<html>Nombre de producto largo6<html>");

        precioPro6.setBackground(new java.awt.Color(255, 255, 255));
        precioPro6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro6.setForeground(new java.awt.Color(0, 0, 0));
        precioPro6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro6.setText("$0.00");

        btnAgregar6.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar6.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar6.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar6.setText("+");
        btnAgregar6.setBorder(null);
        btnAgregar6.setBorderPainted(false);
        btnAgregar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar6.setFocusable(false);
        btnAgregar6.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto6Layout = new javax.swing.GroupLayout(panelProducto6);
        panelProducto6.setLayout(panelProducto6Layout);
        panelProducto6Layout.setHorizontalGroup(
            panelProducto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProducto6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProducto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto6Layout.createSequentialGroup()
                        .addComponent(precioPro6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelProducto6Layout.setVerticalGroup(
            panelProducto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro6)
                    .addComponent(btnAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelProducto7.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto7.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto7.setRoundBottomLeft(10);
        panelProducto7.setRoundBottomRight(10);
        panelProducto7.setRoundTopLeft(10);
        panelProducto7.setRoundTopRight(10);

        imagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen7.setBorder(null);
        imagen7.setBorderPainted(false);
        imagen7.setContentAreaFilled(false);
        imagen7.setFocusable(false);

        nombrePro7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro7.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro7.setText("<html>Nombre de producto largo7<html>");

        precioPro7.setBackground(new java.awt.Color(255, 255, 255));
        precioPro7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro7.setForeground(new java.awt.Color(0, 0, 0));
        precioPro7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro7.setText("$0.00");

        btnAgregar7.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar7.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar7.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar7.setText("+");
        btnAgregar7.setBorder(null);
        btnAgregar7.setBorderPainted(false);
        btnAgregar7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar7.setFocusable(false);
        btnAgregar7.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto7Layout = new javax.swing.GroupLayout(panelProducto7);
        panelProducto7.setLayout(panelProducto7Layout);
        panelProducto7Layout.setHorizontalGroup(
            panelProducto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProducto7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProducto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto7Layout.createSequentialGroup()
                        .addComponent(precioPro7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelProducto7Layout.setVerticalGroup(
            panelProducto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro7)
                    .addComponent(btnAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelProducto8.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto8.setPreferredSize(new java.awt.Dimension(140, 210));
        panelProducto8.setRoundBottomLeft(10);
        panelProducto8.setRoundBottomRight(10);
        panelProducto8.setRoundTopLeft(10);
        panelProducto8.setRoundTopRight(10);

        imagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100x100png.png"))); // NOI18N
        imagen8.setBorder(null);
        imagen8.setBorderPainted(false);
        imagen8.setContentAreaFilled(false);
        imagen8.setFocusable(false);

        nombrePro8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombrePro8.setForeground(new java.awt.Color(0, 0, 0));
        nombrePro8.setText("<html>Nombre de producto largo8<html>");

        precioPro8.setBackground(new java.awt.Color(255, 255, 255));
        precioPro8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        precioPro8.setForeground(new java.awt.Color(0, 0, 0));
        precioPro8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioPro8.setText("$0.00");

        btnAgregar8.setBackground(new java.awt.Color(53, 126, 195));
        btnAgregar8.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnAgregar8.setForeground(new java.awt.Color(254, 192, 5));
        btnAgregar8.setText("+");
        btnAgregar8.setBorder(null);
        btnAgregar8.setBorderPainted(false);
        btnAgregar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar8.setFocusable(false);
        btnAgregar8.setPreferredSize(new java.awt.Dimension(20, 20));
        btnAgregar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProducto8Layout = new javax.swing.GroupLayout(panelProducto8);
        panelProducto8.setLayout(panelProducto8Layout);
        panelProducto8Layout.setHorizontalGroup(
            panelProducto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProducto8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProducto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePro8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProducto8Layout.createSequentialGroup()
                        .addComponent(precioPro8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelProducto8Layout.setVerticalGroup(
            panelProducto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProducto8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagen8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePro8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProducto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioPro8)
                    .addComponent(btnAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoProductosLayout = new javax.swing.GroupLayout(panelFondoProductos);
        panelFondoProductos.setLayout(panelFondoProductosLayout);
        panelFondoProductosLayout.setHorizontalGroup(
            panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoProductosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoProductosLayout.createSequentialGroup()
                        .addComponent(panelProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panelProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFondoProductosLayout.createSequentialGroup()
                        .addComponent(panelProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panelProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(606, Short.MAX_VALUE))
        );
        panelFondoProductosLayout.setVerticalGroup(
            panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        fondo.add(panelFondoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void sincronizarBD(){
        
    }
    
    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed

        String nombre = nombrePro1.getText();
        String pre=precioPro1.getText().substring(1, precioPro1.getText().length());
        
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        String nombre = nombrePro2.getText();
        String pre=precioPro2.getText().substring(1, precioPro2.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        String nombre = nombrePro3.getText();
        String pre=precioPro3.getText().substring(1, precioPro3.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar4ActionPerformed
        String nombre = nombrePro4.getText();
        String pre=precioPro4.getText().substring(1, precioPro4.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar4ActionPerformed

    private void btnAgregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar5ActionPerformed
        String nombre = nombrePro5.getText();
        String pre=precioPro5.getText().substring(1, precioPro5.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar5ActionPerformed

    private void btnAgregar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar6ActionPerformed
        String nombre = nombrePro6.getText();
        String pre=precioPro6.getText().substring(1, precioPro6.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar6ActionPerformed

    private void btnAgregar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar7ActionPerformed
        String nombre = nombrePro7.getText();
        String pre=precioPro7.getText().substring(1, precioPro7.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar7ActionPerformed

    private void btnAgregar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar8ActionPerformed
        String nombre = nombrePro8.getText();
        String pre=precioPro8.getText().substring(1, precioPro8.getText().length());
        float precio = Float.parseFloat(pre);
        
        agregarProductoAlCarrito(nombre, precio);
    }//GEN-LAST:event_btnAgregar8ActionPerformed


public void agregarProductoAlCarrito(String nombre, float precio) {
    
// Verificar si el producto ya está en el carrito
    if (productosEnCarrito.containsKey(nombre)) {
        // Si ya está en el carrito, incrementar la cantidad del spinner
        JSpinner spinner = productosEnCarrito.get(nombre);
        spinner.setValue((int) spinner.getValue() + 1); // Incrementar en 1
    } else {
        // Si no está en el carrito, crear un nuevo panel de producto
        JPanel productoPanel = new JPanel();
        productoPanel.setLayout(new FlowLayout(FlowLayout.LEFT)); // Ajustar el layout para mantener alineación

        // Establecer el tamaño preferido del panel del producto
        productoPanel.setPreferredSize(new java.awt.Dimension(300, 65)); // Ancho: 280, Alto: 65
        productoPanel.setMaximumSize(new java.awt.Dimension(300, 65)); // Evitar que cambie de tamaño
        productoPanel.setBackground(Color.WHITE);

        // Crear los componentes del producto
        JLabel paddin = new JLabel("");
        paddin.setPreferredSize(new java.awt.Dimension(15, 47)); // Ancho: 100, Alto: 47
        JLabel nombreProducto = new JLabel(nombre);
        nombreProducto.setPreferredSize(new java.awt.Dimension(100, 47)); // Ancho: 100, Alto: 47
        nombreProducto.setMaximumSize(new java.awt.Dimension(100, 47)); // Evitar que cambie de tamaño
        JSpinner cantidadSpinner = new JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        DecimalFormat dosDecimales = new DecimalFormat("#.##");
        dosDecimales.format(precio);
        String precioFloat = Float.toString(precio);
        JLabel precioLabel = new JLabel("$" + precioFloat);
        precioLabel.setPreferredSize(new java.awt.Dimension(50, 47)); // Ancho: 100, Alto: 47
        JButton eliminarButton = new JButton();
        eliminarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarButton.setPreferredSize(new java.awt.Dimension(20, 20));
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png")));
        eliminarButton.setBorder(null);
        eliminarButton.setBorderPainted(false);
        eliminarButton.setContentAreaFilled(false);
        eliminarButton.setFocusable(false);

        // Listener para actualizar el precio al cambiar la cantidad
        cantidadSpinner.addChangeListener(e -> {
            int cantidad = (int) cantidadSpinner.getValue();
            Float precioTotal = cantidad * precio;
            precioLabel.setText("$" + dosDecimales.format(precioTotal));
        });

        // Añadir los componentes al panel del producto
        productoPanel.add(paddin);
        productoPanel.add(nombreProducto);
        productoPanel.add(cantidadSpinner);
        productoPanel.add(precioLabel);
        productoPanel.add(eliminarButton);

        // Agregar el panel del producto al panel del carrito
        carritoPanel.add(productoPanel);

        // Actualizar la interfaz gráfica
        carritoPanel.revalidate();
        carritoPanel.repaint();

        // Guardar el producto y su spinner en el HashMap
        productosEnCarrito.put(nombre, cantidadSpinner);

        // Acción para eliminar el producto del carrito
        eliminarButton.addActionListener(e -> {
            carritoPanel.remove(productoPanel);
            productosEnCarrito.remove(nombre); // Eliminar del HashMap
            carritoPanel.revalidate();
            carritoPanel.repaint();
        });
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnAgregar5;
    private javax.swing.JButton btnAgregar6;
    private javax.swing.JButton btnAgregar7;
    private javax.swing.JButton btnAgregar8;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton imagen1;
    private javax.swing.JButton imagen2;
    private javax.swing.JButton imagen3;
    private javax.swing.JButton imagen4;
    private javax.swing.JButton imagen5;
    private javax.swing.JButton imagen6;
    private javax.swing.JButton imagen7;
    private javax.swing.JButton imagen8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePro1;
    private javax.swing.JLabel nombrePro2;
    private javax.swing.JLabel nombrePro3;
    private javax.swing.JLabel nombrePro4;
    private javax.swing.JLabel nombrePro5;
    private javax.swing.JLabel nombrePro6;
    private javax.swing.JLabel nombrePro7;
    private javax.swing.JLabel nombrePro8;
    private javax.swing.JPanel panelFondoProductos;
    private expo.PanelRound panelProducto1;
    private expo.PanelRound panelProducto2;
    private expo.PanelRound panelProducto3;
    private expo.PanelRound panelProducto4;
    private expo.PanelRound panelProducto5;
    private expo.PanelRound panelProducto6;
    private expo.PanelRound panelProducto7;
    private expo.PanelRound panelProducto8;
    private javax.swing.JLabel precioPro1;
    private javax.swing.JLabel precioPro2;
    private javax.swing.JLabel precioPro3;
    private javax.swing.JLabel precioPro4;
    private javax.swing.JLabel precioPro5;
    private javax.swing.JLabel precioPro6;
    private javax.swing.JLabel precioPro7;
    private javax.swing.JLabel precioPro8;
    // End of variables declaration//GEN-END:variables
}
